### ISSUE TITLE
Earth Height Map

### ISSUE THREAD

**Issue by kerbinsphere** [Katniss218/KatnisssCapeCanaveral#3]
If I edit the height map in RSS Textures the game will not load, I also have 16k RSS textures rather than 8k, could you make a 16k modified height map? I keep loading in with the launchpads under ground and only about 15% of the vab visible, if these could be fixed as soon as possible I would appreciate it
![under ground ksc](https://user-images.githubusercontent.com/74269765/98731817-22522a80-2353-11eb-9631-2c30b8a41aa5.png)

**Comment by Katniss218** [comment]
The KCC requires RSS 18.1.2+ and RSS-Textures 18.2+ (it needs the 16-bit heightmap loader, that's why).

Don't clone the repo, download the release. Repo doesn't have the proper heightmap in it because 100MB github limit per file.

The heightmap in the release is 16384 px wide (16k)
